### ISSUE TITLE
获取用户信息的问题。

### ISSUE THREAD

**Issue by pensacola1989** [gavinkwoe/weapp-ide-crack#37]
头像应该是获取用户信息之后，显示出来的。。发现无法获取用户信息，也没报错，好像都没有执行getUserInfo，微信封了？

**Comment by forrest23** [comment]
是不是破解版本的没办法获取？跟踪了下是有错误的

`TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at remoteFunction (<anonymous>:3:14)
    at e.onLoad (http://1627164639.appservice.open.weixin.qq.com/pages/index/index.js:24:5)
    at e.o (http://1627164639.appservice.open.weixin.qq.com/WAService.js:2:16851)
    at g (http://1627164639.appservice.open.weixin.qq.com/WAService.js:2:8838)
    at w (http://1627164639.appservice.open.weixin.qq.com/WAService.js:2:9829)
    at .<anonymous> (http://1627164639.appservice.open.weixin.qq.com/WAService.js:2:11717)
    at http://1627164639.appservice.open.weixin.qq.com/WAService.js:2:21703
    at http://1627164639.appservice.open.weixin.qq.com/WAService.js:1:16921
    at Array.forEach (native)
    at http://1627164639.appservice.open.weixin.qq.com/WAService.js:1:16901`

**Comment by hellozhangran** [comment]
同问，没法得到用户信息，头像展示不出来。。。
